### ISSUE TITLE
ErrorException in ShinobiTrait.php line 123: Undefined variable: permissions

### ISSUE THREAD

**Issue by Friendbg** [cgrossde/Laraguard#1]
Hi,

Thanks for the great product.
I'm new in laravel, and I wanted to implement laraguard in my project to create user roles. When I follow your steps in readme, I put : 
public function __construct()
    {
        $this->middleware('laraguard');
    }
in my ServersController.php . After that when I try to open /servers gives me : ErrorException in ShinobiTrait.php line 123: Undefined variable: permissions.

I have permissions table and roles, role_user etc. Maybe I missed how to implement my account to the right group ? I use https://github.com/caffeinated/shinobi.

Can you help me ?

Thanks alot!

**Comment by cgrossde** [comment]
No this seems like a shinobi problem, please post your issue there. Did you also add a `getPermissions()` method to your User model?

**Comment by cgrossde** [comment]
Closing it due to inactivity, feel free to reopen it.
